USE GD1C2025;
GO


-- Eliminar FK compuesta si existe
IF OBJECT_ID('Detalle_Factura', 'U') IS NOT NULL
BEGIN
    IF EXISTS (
        SELECT * FROM sys.foreign_keys 
        WHERE name = 'fk_detallefactura_pedido'
    )
    BEGIN
        ALTER TABLE Detalle_Factura 
        DROP CONSTRAINT fk_detallefactura_pedido;
    END
END

-- Eliminar todas las tablas (si existen)
DROP TABLE IF EXISTS LOS_HELECHOS.Envio;
DROP TABLE IF EXISTS LOS_HELECHOS.Detalle_Factura;
DROP TABLE IF EXISTS LOS_HELECHOS.Factura;
DROP TABLE IF EXISTS LOS_HELECHOS.CancelacionPedido;
DROP TABLE IF EXISTS LOS_HELECHOS.Detalle_Pedido;
DROP TABLE IF EXISTS LOS_HELECHOS.Pedido;
DROP TABLE IF EXISTS LOS_HELECHOS.Sillon;
DROP TABLE IF EXISTS LOS_HELECHOS.Detalle_Compra;
DROP TABLE IF EXISTS LOS_HELECHOS.Compra;
DROP TABLE IF EXISTS LOS_HELECHOS.Cliente;
DROP TABLE IF EXISTS LOS_HELECHOS.Sucursal;
DROP TABLE IF EXISTS LOS_HELECHOS.Proveedor;
DROP TABLE IF EXISTS LOS_HELECHOS.Localidad;
DROP TABLE IF EXISTS LOS_HELECHOS.Relleno;
DROP TABLE IF EXISTS LOS_HELECHOS.Madera;
DROP TABLE IF EXISTS LOS_HELECHOS.Tela;
DROP TABLE IF EXISTS LOS_HELECHOS.Sillon_Medida;
DROP TABLE IF EXISTS LOS_HELECHOS.Sillon_Modelo;
DROP TABLE IF EXISTS LOS_HELECHOS.Material;
DROP TABLE IF EXISTS LOS_HELECHOS.Provincia;