USE GD1C2025;
GO

-- Eliminar tablas de hechos (en orden para evitar conflictos por FK)
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Hecho_Envio;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Hecho_Pedido;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Hecho_Compra;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Hecho_Venta;

-- Eliminar dimensiones
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_Turno;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_Sillon;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_Cliente;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_Sucursal;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_Tiempo;
DROP TABLE IF EXISTS LOS_HELECHOS.BI_Dim_EstadoPedido;

